<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\DefaultController:loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.iud7pdy']) ? $this->services['service_locator.iud7pdy'] : $this->load('getServiceLocator_Iud7pdyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\Usuario\\UsuarioController:indexEditUsuario' => function () {
    return ${($_ = isset($this->services['service_locator.tzdfprz']) ? $this->services['service_locator.tzdfprz'] : $this->load('getServiceLocator_TzdfprzService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\Usuario\\UsuarioController:indexNuevoUsuario' => function () {
    return ${($_ = isset($this->services['service_locator.yswu2ul']) ? $this->services['service_locator.yswu2ul'] : $this->load('getServiceLocator_Yswu2ulService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\DefaultController::loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.iud7pdy']) ? $this->services['service_locator.iud7pdy'] : $this->load('getServiceLocator_Iud7pdyService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\Usuario\\UsuarioController::indexEditUsuario' => function () {
    return ${($_ = isset($this->services['service_locator.tzdfprz']) ? $this->services['service_locator.tzdfprz'] : $this->load('getServiceLocator_TzdfprzService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\Usuario\\UsuarioController::indexNuevoUsuario' => function () {
    return ${($_ = isset($this->services['service_locator.yswu2ul']) ? $this->services['service_locator.yswu2ul'] : $this->load('getServiceLocator_Yswu2ulService.php')) && false ?: '_'};
})));
