# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 4
#     https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:Usuario
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


#        main:
#            anonymous: ~
#            provider: our_db_provider
#            form_login:
#                login_path: /login
#                check_path: /login_check
##                default_target_path: /login
##                always_use_default_target_path: true
#            logout:
#                path: logout
#                target: /login
##                invalidate_session: true
##                default_target_path: /login
            # activate different ways to authenticate
    access_control:
        - { path: ^/login,  roles:  IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario,  roles:  IS_AUTHENTICATED_FULLY }
        - { path: ^/ticket,  roles:  IS_AUTHENTICATED_FULLY }

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
#            form_login: login
#            check_path: login
