<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8hgj4sz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8hgj4sz/appProdProjectContainer.php') {
    touch(__DIR__.'/Container8hgj4sz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container8hgj4sz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container8hgj4sz\appProdProjectContainer(array(
    'container.build_hash' => '8hgj4sz',
    'container.build_id' => 'ab5332ea',
    'container.build_time' => 1528163240,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8hgj4sz');
