<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.customserializer' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Services/CustomSerializer.php';

return $this->services['app.customserializer'] = new \AppBundle\Services\CustomSerializer();
