<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Services\CustomSerializer' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Services/CustomSerializer.php';

return $this->services['AppBundle\Services\CustomSerializer'] = new \AppBundle\Services\CustomSerializer();
