<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ4uxu5w\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ4uxu5w/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZ4uxu5w.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZ4uxu5w\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZ4uxu5w\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Z4uxu5w',
    'container.build_id' => '56977de7',
    'container.build_time' => 1531587023,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ4uxu5w');
