<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQvpglzo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQvpglzo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQvpglzo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQvpglzo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQvpglzo\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Qvpglzo',
    'container.build_id' => '631edf4d',
    'container.build_time' => 1531791975,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQvpglzo');
